version: "3.8"
services:
  backend:
    build: "."
    container_name: backend
    volumes:
      - ./:/api
    ports:
      - "8000:8000"
    environment:
      - AUTH_SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
    restart: on-failure